# Generated by Django 4.1.7 on 2026-04-23 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='菜品名称')),
                ('category', models.CharField(db_index=True, default='快餐', max_length=50, verbose_name='菜品分类')),
                ('price', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='菜品单价')),
                ('description', models.TextField(blank=True, null=True, verbose_name='菜品简介')),
                ('current_stock', models.IntegerField(default=50, verbose_name='当前库存')),
                ('safety_stock', models.IntegerField(default=15, verbose_name='安全库存阈值')),
            ],
            options={
                'verbose_name': '菜品',
                'verbose_name_plural': '菜品列表',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='订单编号')),
                ('order_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='下单时间')),
                ('item_name', models.CharField(db_index=True, max_length=100, verbose_name='菜品名称')),
                ('category', models.CharField(default='快餐', max_length=50, verbose_name='菜品分类')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易总额')),
                ('payment_method', models.CharField(db_index=True, default='其他/现金', max_length=20, verbose_name='支付方式')),
                ('time_of_sale', models.CharField(db_index=True, default='未知', max_length=20, verbose_name='售卖时段')),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单列表',
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_time'], name='restaurant__order_t_5ec1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['item_name'], name='restaurant__item_na_0e52f8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_time', 'item_name'], name='restaurant__order_t_8cc631_idx'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['category', 'price'], name='restaurant__categor_c7827f_idx'),
        ),
    ]
