# Generated by Django 6.0.3 on 2026-03-15 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="item_name",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="菜品名称"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="item_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="单价",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="quantity",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="数量"
            ),
        ),
    ]
