# Generated by Django 4.1.7 on 2026-04-24 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='数量')),
                ('price_at_purchase', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='下单单价')),
            ],
            options={
                'verbose_name': '订单明细',
                'verbose_name_plural': '订单明细列表',
            },
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='restaurant__item_na_0e52f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='restaurant__order_t_8cc631_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.dish', verbose_name='包含菜品'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.order', verbose_name='所属订单'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='restaurant__order_i_ff851f_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['dish'], name='restaurant__dish_id_1a6424_idx'),
        ),
    ]
