# Generated by Django 4.2.10 on 2026-04-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_order_item_name_order_item_price_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='current_stock',
            field=models.IntegerField(default=50, verbose_name='当前库存'),
        ),
        migrations.AddField(
            model_name='dish',
            name='safety_stock',
            field=models.IntegerField(default=15, verbose_name='安全库存阈值'),
        ),
    ]
