# Generated by Django 4.1.7 on 2026-04-16 15:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_dish_current_stock_dish_safety_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': '订单', 'verbose_name_plural': '订单列表'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='dish',
            name='category',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='price',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='safety_stock',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_price',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='dish',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='category',
            field=models.CharField(default='快餐', max_length=50, verbose_name='菜品分类'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='其他/现金', max_length=20, verbose_name='支付方式'),
        ),
        migrations.AddField(
            model_name='order',
            name='time_of_sale',
            field=models.CharField(default='未知', max_length=20, verbose_name='售卖时段'),
        ),
        migrations.AlterField(
            model_name='order',
            name='item_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='菜品名称'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_time',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='交易总额'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.order', verbose_name='所属订单'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_time', 'item_name'], name='restaurant__order_t_8cc631_idx'),
        ),
    ]
