# Generated by Django 4.1.7 on 2026-04-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_dish_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_time'], name='restaurant__order_t_5ec1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['item_name'], name='restaurant__item_na_0e52f8_idx'),
        ),
    ]
