# Generated by Django 4.1.7 on 2026-04-17 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_order_restaurant__order_t_5ec1f8_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name': '菜品', 'verbose_name_plural': '菜品列表'},
        ),
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(db_index=True, default='快餐', max_length=50, verbose_name='菜品分类'),
        ),
        migrations.AddField(
            model_name='dish',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='菜品简介'),
        ),
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=10, verbose_name='菜品单价'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['category', 'price'], name='restaurant__categor_c7827f_idx'),
        ),
    ]
