# Generated by Django 4.1.7 on 2026-04-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_dish_options_dish_category_dish_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(db_index=True, default='其他/现金', max_length=20, verbose_name='支付方式'),
        ),
        migrations.AlterField(
            model_name='order',
            name='time_of_sale',
            field=models.CharField(db_index=True, default='未知', max_length=20, verbose_name='售卖时段'),
        ),
    ]
