# Generated by Django 4.1.7 on 2026-04-20 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_order_payment_method_alter_order_time_of_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='current_stock',
            field=models.IntegerField(default=50, verbose_name='当前库存'),
        ),
        migrations.AddField(
            model_name='dish',
            name='safety_stock',
            field=models.IntegerField(default=15, verbose_name='安全库存阈值'),
        ),
    ]
