# Generated by Django 4.1.7 on 2026-04-23 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_dish_current_stock_dish_safety_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': '订单明细', 'verbose_name_plural': '订单明细列表'},
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='restaurant__order_t_8cc631_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='restaurant__order_t_5ec1f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='order',
            name='restaurant__item_na_0e52f8_idx',
        ),
        migrations.RemoveField(
            model_name='order',
            name='category',
        ),
        migrations.RemoveField(
            model_name='order',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='restaurant.dish', verbose_name='菜品'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='price_at_order',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='下单时单价'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='数量'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='订单总额'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='restaurant.order', verbose_name='所属订单'),
        ),
    ]
